table MedidasIndicadoresFinanceiros
	lineageTag: 55dded5d-ac9e-4925-8d40-79d450ba942b

	measure TotalReceitas = CALCULATE(SUM(DadosFinanceiros[Valor]),DadosFinanceiros[Tipo] = "Receitas")
		lineageTag: f7803d4e-5ca9-4c81-a64f-aedf068e133e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalDespesas = CALCULATE(SUM(DadosFinanceiros[Valor]),DadosFinanceiros[Tipo] = "Despesas")
		lineageTag: 7f617b8d-8a71-4d52-bd93-6b93f2804dca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Lucro = [TotalReceitas] - [TotalDespesas]
		lineageTag: 76dabea2-3686-49e1-8772-b1e98cc0db86

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure MargemLucro = DIVIDE([Lucro], [TotalReceitas], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f06e9578-d2de-4fef-b737-a717d29c0eda

	partition MedidasIndicadoresFinanceiros = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

