table DadosContabeis
	lineageTag: 0ba59e14-69d9-4cf9-9c19-2996b230fa3a

	column ID_Conta
		dataType: int64
		formatString: 0
		lineageTag: 3e2c6a20-9b8e-4536-ac16-d579ca501c88
		summarizeBy: none
		sourceColumn: ID_Conta

		annotation SummarizationSetBy = Automatic

	column Ano_2019
		dataType: int64
		formatString: 0
		lineageTag: 43452986-2f3c-432e-a936-1f5de2269074
		summarizeBy: sum
		sourceColumn: Ano_2019

		annotation SummarizationSetBy = Automatic

	column Ano_2020
		dataType: double
		lineageTag: 9695def0-6d63-4d3b-8704-2de00908ff11
		summarizeBy: sum
		sourceColumn: Ano_2020

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ano_2021
		dataType: double
		lineageTag: 15726635-f7ac-46f2-b47f-4644ab14b8e2
		summarizeBy: sum
		sourceColumn: Ano_2021

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ano_2022
		dataType: double
		lineageTag: 88b40853-b70b-4bbd-bf00-5ab788aadd08
		summarizeBy: sum
		sourceColumn: Ano_2022

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ano_2023
		dataType: double
		lineageTag: 0ea126bf-39c2-4791-8373-e38fc89719bb
		summarizeBy: sum
		sourceColumn: Ano_2023

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DadosContabeis = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\Maria Eduarda\Desktop\curso-power-bi-data-science-academy\secao09\Dataset.xlsx"), null, true),
				    DadosContabeis_Sheet = Fonte{[Item="DadosContabeis",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(DadosContabeis_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID_Conta", Int64.Type}, {"Ano_2019", Int64.Type}, {"Ano_2020", type number}, {"Ano_2021", type number}, {"Ano_2022", type number}, {"Ano_2023", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

