table Medida
	lineageTag: ad771835-6c54-47d1-bf5e-992f9a525634

	measure TotalEntregas = COUNTROWS(Logistica)
		formatString: 0
		lineageTag: a69deb43-a250-41e7-84de-f596f02e04ab

	measure Rating =
			
			VAR __MAX_NUMBER_OF_STARS = 5
			VAR __MIN_RATED_VALUE = 1500
			VAR __MAX_RATED_VALUE = 2500
			VAR __BASE_VALUE = [TotalEntregas]
			VAR __NORMALIZED_BASE_VALUE =
				MIN(
					MAX(
						DIVIDE(
							__BASE_VALUE - __MIN_RATED_VALUE,
							__MAX_RATED_VALUE - __MIN_RATED_VALUE
						),
						0
					),
					1
				)
			VAR __STAR_RATING = ROUND(__NORMALIZED_BASE_VALUE * __MAX_NUMBER_OF_STARS, 0)
			RETURN
				IF(
					NOT ISBLANK(__BASE_VALUE),
					REPT(UNICHAR(9733), __STAR_RATING)
						& REPT(UNICHAR(9734), __MAX_NUMBER_OF_STARS - __STAR_RATING)
				)
		lineageTag: f91915d9-9cf1-4fee-a810-c1ea3865223d

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "StarRating"
				}

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isText":true}

	measure TotalEntregaPrazo = CALCULATE([TotalEntregas], FILTER(Logistica, Logistica[Status_Entrega] = "Antecipado" || Logistica[Status_Entrega] = "No Prazo" ))
		formatString: 0
		lineageTag: f1800661-ebda-49b7-9988-b3a0978e7d2f

	partition Medida = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

